name: Protect NL-VISION
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Fail if NL-VISION core files changed without override
        run: |
          set -euo pipefail
          # files we protect
          PROTECTED="src/pages/labs/nl-vision.tsx src/components/CareChat.tsx src/components/LiveVitals.tsx"
          # allow override only if commit message includes token
          OVERRIDE_TOKEN="[ALLOW-NLVISION-EDIT]"
          # detect changes in PR
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "Changed files:"
          echo "$CHANGED"
          # if any protected file is in the diff and token not present, fail
          for f in $PROTECTED; do
            if echo "$CHANGED" | grep -qx "$f"; then
              echo "Detected change in protected file: $f"
              # read all commit messages in the PR range
              MSGS=$(git log --pretty=format:%s origin/${{ github.base_ref }}..HEAD)
              if ! echo "$MSGS" | grep -q "$OVERRIDE_TOKEN"; then
                echo "❌ Missing override token $OVERRIDE_TOKEN in commit messages."
                echo "Add the token to one commit message only when you *intentionally* edit NL-VISION."
                exit 1
              fi
            fi
          done
          echo "✅ No unauthorized changes to protected files."
